server.port: 8080

feign.client.config:
  default:
    connectTimeout: 5000
    readTimeout: 5000
    loggerLevel: full

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: false
  jms:
    listener:
      acknowledge-mode: auto
      recovery-interval: 1000 # Interval (in ms) between reconnect attempts to avoid long retries during shutdown
      auto-startup: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  artemis:
    broker-url: tcp://localhost:61616?broker.persistent=true
    user: artemis
    password: simetraehcapa
  cloud:
    config:
      override-system-properties: false
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
      username: root
      password: mongoUser
      database: trips

paymentusecase:
  orchestration:
    strategy: statemachine