logging.level.tech: debug
logging.level.dexter.banking.booktransfers.infrastructure.middleware: debug
logging.level.dexter.banking.booktransfers.core.usecase: info
logging.level.org.springframework.transaction.event: warn

spring:
  jackson:
    # Disable default serialization features that are not needed
    # and might interfere with our custom object mapper configuration.
    # We will rely on our primary ObjectMapper bean.
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
      # The following are often default, but explicitly setting them ensures consistency
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false


# --- Unified Service Configuration for Business Process Journeys ---
service-config:
  journeys:
    PAYMENT_SUBMIT_V1:
      idempotencyEnabled: true
      policies:
        - "stateTransitionPolicy"
    PAYMENT_SUBMIT_V2_SYNC:
      idempotencyEnabled: true
      policies:
        - "stateTransitionPolicy"
    PAYMENT_SUBMIT_V2_ASYNC:
      idempotencyEnabled: false # Fire-and-forget; idempotency is handled by the initial submission
      policies:
        - "stateTransitionPolicy"
