logging.level.tech: debug
logging.level.dexter.banking.booktransfers.infrastructure.middleware: debug
logging.level.dexter.banking.booktransfers.core.usecase: info

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true

# --- Service Configuration is now version-aware ---
service-config:
  commands:
    PAYMENT_SUBMIT_V1:
      idempotencyApplicable: true
    PAYMENT_SUBMIT_V2_SYNC:
      idempotencyApplicable: true # As per your requirement
    PAYMENT_SUBMIT_V2_ASYNC:
      idempotencyApplicable: false # Correct for fire-and-forget
    PROCESS_LIMIT_EARMARK:
      idempotencyApplicable: false
    PROCESS_DEBIT_LEG:
      idempotencyApplicable: false
    PROCESS_CREDIT_LEG:
      idempotencyApplicable: false
    PROCESS_DEBIT_LEG_REVERSAL:
      idempotencyApplicable: false
    PROCESS_LIMIT_EARMARK_REVERSAL:
       idempotencyApplicable: false
