logging:
  level:
    org.springframework.cloud.gateway: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    org.springframework.boot.autoconfigure.web: debug
    reactor.netty: debug

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eurekaUser:eurekaPassword@localhost:8761/eureka/

spring:
  application:
    name: payment-gateway

  sleuth:
    sampler:
      percentage: 1.0

  zipkin:
    base-url: http://localhost:9411/

  cloud:

    # Debug routes
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true

      routes:

      - id: book-transfers-service
        uri: lb://book-transfers-service
        predicates:
        - Path=/api/v1/book-transfers/payment,/api/v1/book-transfers/payment/{id},/api/v2/book-transfers/payment,/api/v2/book-transfers/payment/{id}

      - id: deposit-banking-service
        uri: lb://deposit-banking-service
        predicates:
        - Path=/api/v1/deposit-banking,/api/v1/deposit-banking/{depositId},/api/v1/deposit-banking/{depositId}/cancelled

      - id: limit-management-service
        uri: lb://limit-management-service
        predicates:
        - Path=/api/v1/limit-management,/api/v1/limit-management/{limitId},/api/v1/limit-management/{limitId}/cancelled

      - id: credit-card-banking-service
        uri: lb://credit-card-banking-service
        predicates:
          - Path=/api/v1/credit-card-banking,/api/v1/credit-card-banking/{creditCardId},/api/v1/credit-card-banking/{creditCardId}/cancelled