server:
  port: 8761

spring:
  application:
    name: payment-eureka-server
  security:
    user:
      name: eurekaUser
      password: eurekaPassword

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF