spring:
  profiles:
    active: mongo, idempotency-redis
  application:
    name: book-transfers-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: payment-config-server
      fail-fast: true
      username: configUser
      password: configPassword
  jms:
    listener:
      concurrency: 5
      max-concurrency: 10
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
    logging:
      enabled: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eurekaUser:eurekaPassword@localhost:8761/eureka/

app:
  journeys:
    PAYMENT_SUBMIT_V1:
      journeyType: "STANDARD_PAYMENT"
      validationGroups: ["STANDARD_PAYMENT"]
      policies: ["stateTransitionPolicy"]
      dataCollectors: ["accountBalanceDataCollector", "customerProfileDataCollector"]
      businessRules: []
      adapterRouting:
        depositPort: "DEBIT_PORT_FEIGN"
        creditCardPort: "CREDIT_PORT_FEIGN"
        limitPort: "LIMIT_PORT_FEIGN"
      feature-flag:
        enabled: true
        pilot-groups:
          - BETA_TESTERS
    PAYMENT_SUBMIT_V2_ASYNC:
      journeyType: "ORCHESTRATED_PAYMENT"
      idempotencyEnabled: false
      validationGroups: ["STANDARD_PAYMENT"]
      policies: ["stateTransitionPolicy"]
      dataCollectors: ["accountBalanceDataCollector", "customerProfileDataCollector"]
      businessRules: []
      orchestration:
        engine: "asyncTransactionFsmFactory"
      adapterRouting:
        transactionLegPort: "TRANSACTION_LEG_PORT_JMS"
      feature-flag:
        enabled: true
    PAYMENT_SUBMIT_V2_ASYNC_CALLBACK:
      journeyType: "ORCHESTRATED_PAYMENT"
      idempotencyEnabled: false
      validationGroups: ["STANDARD_PAYMENT"]
      policies: ["stateTransitionPolicy"]
      dataCollectors: []
      businessRules: []
      orchestration:
        engine: "asyncTransactionFsmFactory"
      adapterRouting:
        transactionLegPort: "TRANSACTION_LEG_PORT_JMS"

feature-flags:
  group-assignments:
    BETA_TESTERS:
      - "1312133"
      - "1312134"
    INTERNAL_AUDITORS:
      - "1312134"
    ADS_USERS:
      - "1312134"

logging:
  level:
    tech: debug
    dexter.banking.booktransfers.infrastructure.middleware: debug
    dexter.banking.booktransfers.core.usecase: info
    org.springframework.transaction.event: warn
