version: '3.1'

services:
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ACTIVEMQ_DEFAULT_USER: admin
      ACTIVEMQ_DEFAULT_PASSWORD: admin
    networks:
        - spring
  zipkin:
    image: openzipkin/zipkin-slim
    ports:
      - 9411:9411
    networks:
      - spring
  mongo:
    image: mongo:3.6.23
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoUser
    networks:
      - spring
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8091:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoUser
    networks:
      - spring

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge