logging.level.tech: debug

spring:
  jms:
    listener:
      concurrency: 5
      max-concurrency: 10
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true