server.port: 8081

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true
    pool:
      enabled: false
  jms:
    listener:
      acknowledge-mode: auto
      recovery-interval: 1000 # Interval (in ms) between reconnect attempts to avoid long retries during shutdown
      auto-startup: true
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  cloud:
    config:
      override-system-properties: false

  # defaults for this docker image - vromero/activemq-artemis
  artemis:
    user: artemis
    password: simetraehcapa